# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'XDSwift' do

	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'Kingfisher'
	pod 'MJRefresh'
	pod 'KakaJSON'

end
